name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: darkness0710/ruby_mysql
      volumes: 
         - ${{ github.workspace }}:/var/www
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Restart mysql service
        run: service mysql restart
      - name: Install gem
        run: bundle install
      - name: Migrate database
        run: bundle exec rake db:drop db:create db:migrate
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
