name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: darkness0710/blog_ruby_mysql
      volumes: 
        - ./:/var/www
    env:
      RAILS_ENV: test
    steps:
      - name: Set up database schema
        run: cd /var/www && bundle install && bundle exec rake db:drop db:create db:migrate
      - name: Run tests
        run: cd /var/www && bundle exec rspec
