name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: darkness0710/blog_ruby_mysql
    env:
      RAILS_ENV: test
    steps:
      - name: Run tests
        with:
          image: darkness0710/blog_ruby_mysql
          options: -v ${{ github.workspace }}:/var/www
          run: |
            bundle install && bundle exec rake db:drop db:create db:migrate
            bundle exec rspec
